name: Build Page

on:
  push:
    branches:
      - main

jobs:
  build:
    name: deploy-building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.17.0'

      - name: install pkg
        run: npm install 

      - name: build pages
        run: npm run build

      - name: ssh deploy guigu
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.SERVER_IP }} # 服务器的ip
          user: ${{ secrets.SERVER_NAME }} # 服务器的账号
          pass: ${{ secrets.SERVER_PWD }} # 服务器的密码
          connect_timeout: 10s
          first_ssh: | #这部分是在服务器上，传输文件前执行的命令，关闭并删除运行中的旧版本
            cd /root/Github/hunyuan-api
            rm -rf dist-old
            mv dist dist-old
          scp: | #将build生成的文件从GitHub服务器的相应目录，传到我服务器的相应目录
            ./dist => /root/Github/hunyuan-api
          last_ssh: | #这部分是在服务器上，传输文件后执行的命令，新版本重新安装依赖并运行
            pm2 restart hunyuan-api
            exit
